# Generated by Django 4.2.11 on 2024-03-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='学号')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(blank=True, choices=[('男', '男'), ('女', '女')], max_length=10, verbose_name='性别')),
                ('class_name', models.CharField(blank=True, max_length=50, verbose_name='所在班级')),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
